-- CREATE SEQUENCE user_sequence;

CREATE TABLE USER
(
--     ID      BIGINT default user_sequence.nextval primary key NOT NULL,
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NAME CHAR NOT NULL,
    SURNAME CHAR NOT NULL,
    AGE INT NOT NULL
);

INSERT INTO USER (ID, NAME, SURNAME, AGE)
VALUES (1, 'Vasiliy', 'Drugov', 30);