//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.08 at 09:41:22 PM MSK 
//


package net.medrag.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SkillLevel.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SkillLevel"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Null"/&gt;
 *     &lt;enumeration value="Low"/&gt;
 *     &lt;enumeration value="Amateur"/&gt;
 *     &lt;enumeration value="Advanced"/&gt;
 *     &lt;enumeration value="Pro"/&gt;
 *     &lt;enumeration value="Godlike"/&gt;
 *     &lt;enumeration value="BeyondGodlike"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SkillLevel")
@XmlEnum
public enum SkillLevel {

    @XmlEnumValue("Null")
    NULL("Null"),
    @XmlEnumValue("Low")
    LOW("Low"),
    @XmlEnumValue("Amateur")
    AMATEUR("Amateur"),
    @XmlEnumValue("Advanced")
    ADVANCED("Advanced"),
    @XmlEnumValue("Pro")
    PRO("Pro"),
    @XmlEnumValue("Godlike")
    GODLIKE("Godlike"),
    @XmlEnumValue("BeyondGodlike")
    BEYOND_GODLIKE("BeyondGodlike");
    private final String value;

    SkillLevel(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SkillLevel fromValue(String v) {
        for (SkillLevel c: SkillLevel.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
