//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.12 at 11:01:51 PM MSK 
//


package net.medrag.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.medrag.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Developer_QNAME = new QName("http://schema.medrag.net", "Developer");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.medrag.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Developer }
     * 
     */
    public Developer createDeveloper() {
        return new Developer();
    }

    /**
     * Create an instance of {@link SkillList }
     * 
     */
    public SkillList createSkillList() {
        return new SkillList();
    }

    /**
     * Create an instance of {@link Skill }
     * 
     */
    public Skill createSkill() {
        return new Skill();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Developer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Developer }{@code >}
     */
    @XmlElementDecl(namespace = "http://schema.medrag.net", name = "Developer")
    public JAXBElement<Developer> createDeveloper(Developer value) {
        return new JAXBElement<Developer>(_Developer_QNAME, Developer.class, null, value);
    }

}
