//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.03 at 04:02:50 PM MSK 
//


package net.medrag.schematypes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.medrag.schematypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeveloperRequest_QNAME = new QName("http://schemaTypes.medrag.net", "DeveloperRequest");
    private final static QName _DeveloperResponse_QNAME = new QName("http://schemaTypes.medrag.net", "DeveloperResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.medrag.schematypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeveloperRequestType }
     * 
     */
    public DeveloperRequestType createDeveloperRequestType() {
        return new DeveloperRequestType();
    }

    /**
     * Create an instance of {@link DeveloperResponseType }
     * 
     */
    public DeveloperResponseType createDeveloperResponseType() {
        return new DeveloperResponseType();
    }

    /**
     * Create an instance of {@link Fehler }
     * 
     */
    public Fehler createFehler() {
        return new Fehler();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeveloperRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeveloperRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemaTypes.medrag.net", name = "DeveloperRequest")
    public JAXBElement<DeveloperRequestType> createDeveloperRequest(DeveloperRequestType value) {
        return new JAXBElement<DeveloperRequestType>(_DeveloperRequest_QNAME, DeveloperRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeveloperResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeveloperResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemaTypes.medrag.net", name = "DeveloperResponse")
    public JAXBElement<DeveloperResponseType> createDeveloperResponse(DeveloperResponseType value) {
        return new JAXBElement<DeveloperResponseType>(_DeveloperResponse_QNAME, DeveloperResponseType.class, null, value);
    }

}
