{
 "title": "Misc-G-App Business Metrics",
 "time": { "from": "2021-12-26T11:15:57.366Z", "to": "2021-12-26T23:15:57.366Z" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Average visiting time",
   "type": "gauge",
   "description": "in seconds.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "average_visiting_time / 1000000000"
    }
   ]
  },
  {
   "title": "Visitors delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "delta(visitor_ages_total{age=\"out of estimation\",}[5m])",
     "legendFormat": "invalid age visitors"
    },
    {
     "expr": "delta(visitor_ages_total{age=\"old\",}[5m])",
     "legendFormat": "51-100 age visitors"
    },
    {
     "expr": "delta(visitor_ages_total{age=\"young\",}[5m])",
     "legendFormat": "31-50 age visitors"
    },
    {
     "expr": "delta(visitor_ages_total{age=\"teenage\",}[5m])",
     "legendFormat": "21-30 age visitors"
    },
    {
     "expr": "delta(visitor_ages_total{age=\"adult\",}[5m])",
     "legendFormat": "below 20 age visitors"
    }
   ]
  },
  {
   "title": "Average visitors age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "average_visitors_age_sum / average_visitors_age_count"
    }
   ]
  },
  {
   "title": "Average visiting time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "average_visiting_time / 1000000000"
    },
    {
     "expr": "(visiting_time_seconds_sum / visiting_time_seconds_count) * 0.1"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "tasks_active", "legendFormat": "active tasks" },
    { "expr": "tasks_started_total", "legendFormat": "started tasks" },
    { "expr": "tasks_successful_total", "legendFormat": "successful tasks" },
    { "expr": "tasks_invalid_total", "legendFormat": "invalid tasks" }
   ]
  },
  {
   "title": "Average Task Completion Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "tasks_completion_time_seconds_sum / tasks_completion_time_seconds_count"
    }
   ]
  },
  {
   "title": "Inversions Number",
   "type": "stat",
   "description": "Total number of inversions",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "inversions_total" }
   ]
  },
  {
   "title": "Average inversion time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inversions_time_seconds_sum / inversions_time_seconds_count"
    }
   ]
  },
  {
   "title": "Average long-term task execution time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tasks_total_time_seconds_duration_sum / tasks_total_time_seconds_active_count"
    }
   ]
  }
 ]
}