apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaxbexample.fullname" . }}
  labels:
    {{- include "jaxbexample.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "jaxbexample.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}