FROM maven:3.8.6-jdk-11 AS mvn-build
ARG MVN_PROFILE=default
ARG EXTRA_KEYS=-Dmaven.test.skip=true
ENV BUILDKIT_STEP_LOG_MAX_SIZE=-1
ENV SERVER_PORT=34343
# Project root is workdir according to the command.
COPY . /root/application

WORKDIR /root/application
RUN mvn clean install $EXTRA_KEYS -P$MVN_PROFILE

FROM openjdk:11.0.16-jre AS deployment
COPY --from=mvn-build root/application/bombarder/target/*.jar /application.jar
EXPOSE $SERVER_PORT
ENTRYPOINT ["java","-jar","/application.jar"]