CREATE TABLE IF NOT EXISTS PAYMENT
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    AMOUNT INT DEFAULT 0 NOT NULL CHECK ( AMOUNT > 0 ),
    SENDER BIGINT NOT NULL CHECK ( SENDER > 0 ),
    RECIPIENT BIGINT NOT NULL CHECK ( RECIPIENT > 0 )
);