//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.13 at 10:56:17 AM MSK 
//


package org.w3._2001.xmlschema;

import java.time.LocalDateTime;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, LocalDateTime>
{


    public LocalDateTime unmarshal(String value) {
        return (net.medrag.devBuilder.service.xml.adapter.StaticLocalDateTimeAdapter.unmarshal(value));
    }

    public String marshal(LocalDateTime value) {
        return (net.medrag.devBuilder.service.xml.adapter.StaticLocalDateTimeAdapter.marshal(value));
    }

}
