ktapp:
  monitoring:
    incoming-requests:
      config:
        enabled: true
        percentiles-enabled: true
        slo-enabled: true
        percentiles: [ 0.5,0.75,0.9,0.95,0.99 ]
        slo: [ 10ms,25ms,50ms,100ms,200ms,500ms,1000ms,1500ms,2000ms,3000ms,5000ms ]
        custom-slo:
          "[/post-it]": [ 200ms,300ms,400ms,500ms,600ms,700ms,1000ms,1500ms,2000ms,3000ms,5000ms ]
          "[/put-it]": [ 250ms,350ms,450ms,650ms,900ms,1500ms,3000ms,5000ms ]